---
title: "Class Objectives"
format: docx
editor: visual
---

## Goals of this document

We will treat this class more like a job. There will not be tests or quizzes. Rather we will have conversations where we discuss how you are doing, and what you could improve on. You will reflect on your work, I will reply and we will discuss your grade from there.

We can discuss amendment of objectives as well, especially your personal objectives.

## Basic objectives

Over the course it is expected you will:

**Technically**

1.  Understand and implement the basic R-Studio -\> GitHub workflow; be able to collaborate using GitHub.
2.  Work in Quarto files; be able to adjust format and make output look nice.
3.  Complete https://swcarpentry.github.io/r-novice-gapminder/index.html
4.  Develop slideshow and website.
5.  Use code to further your own research.

**Communications**

1.  Provide respectful feedback in class and on Slack.
2.  Assist with issues on in class and on Slack.

## Personal objectives

-   Write everything in Quarto
-   Complete a workflowR website https://workflowr.github.io/workflowr/

## Progress tracking

-   Met week of February 6, 2024

My main goal in this class is not necessarily to know how to do specific tasks from memory, but rather to understand how to approach R, figure out where to start on specific tasks, and get better at troubleshooting. So far, I think I have achieved these goals. Although I think I work slower at computer problems than othere students, I have been able to eventually figure out any issues and complete all the tasks I have attempted so far.

I think my understanding of how to approach R has increased dramatically. I now understand the basic steps of creating and manipulating datasets, including the general steps to modify and visualize data in different ways. These skills are very useful and in the past when I had previously tried to learn R, I didn't even get as far as making a dataframe. Therefore, I think I have made great progress relative to my starting point.

Although I might not ultimately end up with as polished a product, and may take much longer to complete tasks, I am proud of the work I have put in to practice these skills and get more comfortable with the program. My current level of understanding of R and what it can do will definitely allow me to use it in the future, instead of using brute force to accomplish data analysis in excel, which is what I used to have to do.
